name: check_postage_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  dropdown_search: 5.0.3
  http: 0.13.5
  either_dart: ^0.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+3

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/art/
